GET http://localhost:3000/products

###

POST  http://localhost:3000
content-type: application/json

# {
    
#     "title": "qwqwqw",
#     "price": 520
# }

###

# GET http://localhost:3000/2

GET http://localhost:3000/products/5